services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/uba/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/uba/data/wordpress
      o: bind