services:

  #* Mandatory part
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - wordpress
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - .env
    depends_on:
      - mariadb

  #* Bonus part
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    env_file:
      - .env
  ftp:
    build: ./requirements/bonus/ftp
    container_name: ftp
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/home/wordpress
    ports:
      - 21:21
      - 20:20
      - "20000-20010:20000-20010"
  static-website:
    build: ./requirements/bonus/static_website
    container_name: static-website
    restart: always
    ports:
      - 3000:3000
  adminer:
    build: ./requirements/bonus/adminer/
    container_name: adminer
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
  cadvisor:
    build: ./requirements/bonus/cadvisor
    container_name: cadvisor
    restart: always
    ports:
      - 8080:8080

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/uba/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/uba/data/wordpress
      o: bind